### ISSUE TITLE
Create User password validation check error

### ISSUE THREAD

**Issue by Fabian9799** [streamlux/vscode-appwrite#11]
If i try to create a user the message shows "Password must be at least 6 characters long" and the error message disappears after 7 characters instead of 6

**Comment by alexweininger** [comment]
Thanks for reporting this issue! I will confirm the password requirements with the Appwrite team.

**Comment by eldadfux** [comment]
@alexweininger I can confirm the password has to be between 6-32 chars:

https://appwrite.io/docs/client/account#accountCreate

![image](https://user-images.githubusercontent.com/1297371/116803496-d1143e00-ab20-11eb-90fc-d7c3576dad83.png)

**Comment by alexweininger** [comment]
@eldadfux Just to make sure, it's between 6 and 32 chars **inclusive** or **exclusive**?

e.g. is it length >= 6 && length <= 32?

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/116803550-60215600-ab21-11eb-84fb-d83152fdf4cf.png)

Inclusive. 6 chars strings and 32 chars strings are valid. 5 chars and 33 chars are not valid.
