### ISSUE TITLE
Error when trying to delete user

### ISSUE THREAD

**Issue by aadarshadhakalg** [streamlux/vscode-appwrite#17]
When I tried to delete user from the vscode, error was thrown

```
Error running command vscode-appwrite.DeleteUser: Running the contributed command: 'vscode-appwrite.DeleteUser' failed.. This is likely caused by the extension that contributes vscode-appwrite.DeleteUser.
```

output of code --version

```
1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64
```

Extension version: 0.1.0

**Comment by alexweininger** [comment]
Thanks for reporting the issue, I'm looking into this now!

**Comment by alexweininger** [comment]
@aadarshadhakalg The bug has been fixed and I will release a new version of the extension with the fix soon! Thanks again!
