### ISSUE TITLE
Add array rule to collection

### ISSUE THREAD

**Issue by Maatteogekko** [streamlux/vscode-appwrite#20]
When creating a rule there is no option to make it an array.
Also I could't find a way to select which collections are allowed for the document type.

**Comment by alexweininger** [comment]
While I add the array option, as well as the collection option, I will also add the ability to set the default value.

Relevant Appwrite documentation page: https://appwrite.io/docs/rules
<img width="768" alt="Screen Shot 2021-06-03 at 3 14 08 AM" src="https://user-images.githubusercontent.com/12476526/120628653-ca2b6480-c419-11eb-92d8-96a445992a30.png">
